name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TEST_REDIS_ADDR: 'redis:6379'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    container: ${{ matrix.container }}

    strategy:
      matrix:
        container:
        - 'golang:1.13'
        service:
        - 'redis:5'
        - 'redis:6'
        - 'redis:7'

    services:
      redis:
        image: ${{ matrix.service }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -v ./...
