name: Go

on:
  push:
    branches: [ "master", "v2" ]
  pull_request:
    branches: [ "master", "v2" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    container: ${{ matrix.container }}

    strategy:
      matrix:
        container:
        - 'golang:1.20-alpine'
        service:
        - 'redis:5'
        - 'redis:6'
        - 'redis:7'
        - 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.0.0'

    services:
      redis:
        image: ${{ matrix.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -v ./...
        env:
          TEST_REDIS_ADDR: 'redis:6379'
