name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix
        redis:
        - 'latest'
        - '6.0'
        - '5.0'
        - '4.0'
    name: server ${{ matrix.redis }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./cmd/...

    - name: Setup Redis server
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis }}
        auto-start: "true"

    - name: Test
      run: go test -v ./...
